alter table public.cities
  add column if not exists ibge_code text,
  add column if not exists state_name text;

create unique index if not exists cities_ibge_code_unique_idx
  on public.cities(ibge_code)
  where ibge_code is not null;

create index if not exists cities_state_name_idx on public.cities(state, name);

create table if not exists public.city_neighborhoods (
  id bigint generated by default as identity primary key,
  city_id bigint not null references public.cities(id) on delete cascade,
  name text not null,
  slug text not null,
  created_at timestamptz not null default now(),
  unique(city_id, slug)
);

create index if not exists city_neighborhoods_city_name_idx
  on public.city_neighborhoods(city_id, name);

alter table public.ads
  add column if not exists hours text,
  add column if not exists plan_slug text default 'basico';

alter table public.city_neighborhoods enable row level security;

grant select on table public.city_neighborhoods to anon, authenticated;
grant insert on table public.city_neighborhoods to authenticated;
grant usage, select on sequence public.city_neighborhoods_id_seq to authenticated;

drop policy if exists "Read city neighborhoods" on public.city_neighborhoods;
create policy "Read city neighborhoods" on public.city_neighborhoods
for select to anon, authenticated using (true);

drop policy if exists "Authenticated users add city neighborhoods" on public.city_neighborhoods;
create policy "Authenticated users add city neighborhoods" on public.city_neighborhoods
for insert to authenticated with check (true);
