create table if not exists public.admin_users (
  id bigint generated by default as identity primary key,
  email text not null unique,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

insert into public.admin_users (email, active)
values ('contato@privacylog.com.br', true)
on conflict (email) do update
set active = excluded.active;

create table if not exists public.admin_audit_logs (
  id bigint generated by default as identity primary key,
  actor_id uuid,
  actor_email text,
  action text not null,
  table_name text not null,
  row_id text,
  details jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nickname text unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  nickname_changed_at timestamptz
);

alter table public.profiles
  add column if not exists nickname text unique,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now(),
  add column if not exists nickname_changed_at timestamptz;

create index if not exists admin_audit_logs_created_at_idx
  on public.admin_audit_logs(created_at desc);

create index if not exists admin_audit_logs_actor_id_idx
  on public.admin_audit_logs(actor_id);

create or replace function public.is_admin()
returns boolean
language sql
stable
set search_path = public
as $$
  select coalesce(
    nullif(auth.jwt() -> 'app_metadata' ->> 'role', '') in ('admin', 'owner')
    or coalesce(auth.jwt() -> 'app_metadata' -> 'roles', '[]'::jsonb) ? 'admin'
    or lower(coalesce(auth.jwt() ->> 'email', '')) = 'contato@privacylog.com.br'
    or exists (
      select 1
      from public.admin_users admin_user
      where admin_user.active = true
        and lower(admin_user.email) = lower(coalesce(auth.jwt() ->> 'email', ''))
    ),
    false
  );
$$;

grant execute on function public.is_admin() to anon, authenticated;

alter table public.admin_users enable row level security;
alter table public.admin_audit_logs enable row level security;
alter table public.clinicas enable row level security;
alter table public.forum_ads enable row level security;
alter table public.forum_categories enable row level security;
alter table public.forum_topics enable row level security;
alter table public.forum_replies enable row level security;
alter table public.profiles enable row level security;

revoke insert, update, delete on table public.clinicas from anon;
revoke insert, update, delete on table public.forum_ads from anon;
revoke insert, update, delete on table public.forum_categories from anon;
revoke insert, update, delete on table public.forum_topics from anon;
revoke insert, update, delete on table public.forum_replies from anon;
revoke select on table public.profiles from anon, authenticated;
revoke delete on table public.profiles from anon, authenticated;

grant select on table public.clinicas to anon, authenticated;
grant insert, update, delete on table public.clinicas to authenticated;

grant select on table public.forum_ads to anon, authenticated;
grant insert, update, delete on table public.forum_ads to authenticated;

grant select on table public.forum_categories to anon, authenticated;
grant insert, update, delete on table public.forum_categories to authenticated;

grant select on table public.forum_topics to anon, authenticated;
grant insert, update, delete on table public.forum_topics to authenticated;

grant select on table public.forum_replies to anon, authenticated;
grant insert, update, delete on table public.forum_replies to authenticated;

grant select (id, nickname) on table public.profiles to anon;
grant select (id, nickname, nickname_changed_at, created_at, updated_at) on table public.profiles to authenticated;
grant insert (id, nickname) on table public.profiles to authenticated;
grant update (nickname, nickname_changed_at, updated_at) on table public.profiles to authenticated;

grant select on table public.admin_users to authenticated;
grant select, insert on table public.admin_audit_logs to authenticated;

do $$
begin
  if to_regclass('public.clinicas_id_seq') is not null then
    grant usage, select on sequence public.clinicas_id_seq to authenticated;
  end if;

  if to_regclass('public.forum_ads_id_seq') is not null then
    grant usage, select on sequence public.forum_ads_id_seq to authenticated;
  end if;

  if to_regclass('public.forum_categories_id_seq') is not null then
    grant usage, select on sequence public.forum_categories_id_seq to authenticated;
  end if;

  if to_regclass('public.forum_topics_id_seq') is not null then
    grant usage, select on sequence public.forum_topics_id_seq to authenticated;
  end if;

  if to_regclass('public.forum_replies_id_seq') is not null then
    grant usage, select on sequence public.forum_replies_id_seq to authenticated;
  end if;

  if to_regclass('public.admin_audit_logs_id_seq') is not null then
    grant usage, select on sequence public.admin_audit_logs_id_seq to authenticated;
  end if;
end $$;

drop policy if exists "Admin users can read own admin row" on public.admin_users;
create policy "Admin users can read own admin row"
on public.admin_users
for select
to authenticated
using (
  lower(email) = lower(coalesce(auth.jwt() ->> 'email', ''))
  or nullif(auth.jwt() -> 'app_metadata' ->> 'role', '') in ('admin', 'owner')
  or coalesce(auth.jwt() -> 'app_metadata' -> 'roles', '[]'::jsonb) ? 'admin'
);

drop policy if exists "Admin audit logs are admin readable" on public.admin_audit_logs;
create policy "Admin audit logs are admin readable"
on public.admin_audit_logs
for select
to authenticated
using (public.is_admin());

drop policy if exists "Admin audit logs are admin insertable" on public.admin_audit_logs;
create policy "Admin audit logs are admin insertable"
on public.admin_audit_logs
for insert
to authenticated
with check (public.is_admin());

drop policy if exists "Clinics are publicly readable" on public.clinicas;
create policy "Clinics are publicly readable"
on public.clinicas
for select
to anon, authenticated
using (true);

drop policy if exists "Admins can insert clinics" on public.clinicas;
create policy "Admins can insert clinics"
on public.clinicas
for insert
to authenticated
with check (public.is_admin());

drop policy if exists "Admins can update clinics" on public.clinicas;
create policy "Admins can update clinics"
on public.clinicas
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins can delete clinics" on public.clinicas;
create policy "Admins can delete clinics"
on public.clinicas
for delete
to authenticated
using (public.is_admin());

drop policy if exists "Public profiles expose nickname only" on public.profiles;
create policy "Public profiles expose nickname only"
on public.profiles
for select
to anon, authenticated
using (true);

drop policy if exists "Users can insert own profile" on public.profiles;
create policy "Users can insert own profile"
on public.profiles
for insert
to authenticated
with check ((select auth.uid()) = id);

drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can update own profile"
on public.profiles
for update
to authenticated
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id);

drop policy if exists "Active forum ads are readable" on public.forum_ads;
create policy "Active forum ads are readable"
on public.forum_ads
for select
to anon, authenticated
using (coalesce(ativo, false) = true or public.is_admin());

drop policy if exists "Admins can manage forum ads" on public.forum_ads;
create policy "Admins can manage forum ads"
on public.forum_ads
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Forum categories are readable" on public.forum_categories;
create policy "Forum categories are readable"
on public.forum_categories
for select
to anon, authenticated
using (true);

drop policy if exists "Authenticated users can insert forum categories" on public.forum_categories;
drop policy if exists "Authenticated users can update forum categories" on public.forum_categories;

drop policy if exists "Admins can insert forum categories" on public.forum_categories;
create policy "Admins can insert forum categories"
on public.forum_categories
for insert
to authenticated
with check (public.is_admin());

drop policy if exists "Admins can update forum categories" on public.forum_categories;
create policy "Admins can update forum categories"
on public.forum_categories
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins can delete forum categories" on public.forum_categories;
create policy "Admins can delete forum categories"
on public.forum_categories
for delete
to authenticated
using (public.is_admin());

drop policy if exists "Forum topics are readable" on public.forum_topics;
create policy "Forum topics are readable"
on public.forum_topics
for select
to anon, authenticated
using (coalesce(oculto, false) = false or public.is_admin());

drop policy if exists "Anyone can create visible topics" on public.forum_topics;
drop policy if exists "Authenticated users can create visible topics" on public.forum_topics;
create policy "Authenticated users can create visible topics"
on public.forum_topics
for insert
to authenticated
with check (
  category_id is not null
  and user_id is not null
  and (select auth.uid()) = user_id
  and length(btrim(titulo)) between 4 and 120
  and length(btrim(conteudo)) between 10 and 8000
  and (nota is null or (nota >= 1 and nota <= 5))
  and coalesce(oculto, false) = false
  and coalesce(fixado, false) = false
  and coalesce(trancado, false) = false
);

drop policy if exists "Admins can update forum topics" on public.forum_topics;
create policy "Admins can update forum topics"
on public.forum_topics
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins can delete forum topics" on public.forum_topics;
create policy "Admins can delete forum topics"
on public.forum_topics
for delete
to authenticated
using (public.is_admin());

drop policy if exists "Forum replies are readable" on public.forum_replies;
create policy "Forum replies are readable"
on public.forum_replies
for select
to anon, authenticated
using (coalesce(oculto, false) = false or public.is_admin());

drop policy if exists "Anyone can create visible replies" on public.forum_replies;
drop policy if exists "Authenticated users can create visible replies" on public.forum_replies;
create policy "Authenticated users can create visible replies"
on public.forum_replies
for insert
to authenticated
with check (
  topic_id is not null
  and user_id is not null
  and (select auth.uid()) = user_id
  and length(btrim(conteudo)) between 2 and 8000
  and coalesce(oculto, false) = false
  and exists (
    select 1
    from public.forum_topics topic
    where topic.id = forum_replies.topic_id
      and coalesce(topic.oculto, false) = false
      and coalesce(topic.trancado, false) = false
  )
);

drop policy if exists "Admins can update forum replies" on public.forum_replies;
create policy "Admins can update forum replies"
on public.forum_replies
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins can delete forum replies" on public.forum_replies;
create policy "Admins can delete forum replies"
on public.forum_replies
for delete
to authenticated
using (public.is_admin());

create or replace function public.enforce_forum_topic_security()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if auth.uid() is null or new.user_id is null or new.user_id <> auth.uid() then
    raise exception 'login_required'
      using errcode = 'P0001';
  end if;

  if not public.is_admin() and exists (
    select 1
    from public.forum_topics topic
    where topic.user_id = new.user_id
      and topic.created_at > now() - interval '60 seconds'
  ) then
    raise exception 'topic_rate_limit'
      using errcode = 'P0001',
            detail = 'Aguarde 60 segundos antes de criar outro tópico.';
  end if;

  return new;
end;
$$;

create or replace function public.enforce_forum_reply_security()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if auth.uid() is null or new.user_id is null or new.user_id <> auth.uid() then
    raise exception 'login_required'
      using errcode = 'P0001';
  end if;

  if not public.is_admin() and exists (
    select 1
    from public.forum_replies reply
    where reply.user_id = new.user_id
      and reply.created_at > now() - interval '30 seconds'
  ) then
    raise exception 'reply_rate_limit'
      using errcode = 'P0001',
            detail = 'Aguarde 30 segundos antes de responder novamente.';
  end if;

  return new;
end;
$$;

drop trigger if exists enforce_forum_topic_security on public.forum_topics;
create trigger enforce_forum_topic_security
before insert on public.forum_topics
for each row execute function public.enforce_forum_topic_security();

drop trigger if exists enforce_forum_reply_security on public.forum_replies;
create trigger enforce_forum_reply_security
before insert on public.forum_replies
for each row execute function public.enforce_forum_reply_security();

create or replace function public.log_admin_change()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  changed_row jsonb;
  changed_id text;
begin
  if not public.is_admin() then
    if tg_op = 'DELETE' then
      return old;
    end if;

    return new;
  end if;

  if tg_op = 'DELETE' then
    changed_row := to_jsonb(old);
  else
    changed_row := to_jsonb(new);
  end if;

  changed_id := changed_row ->> 'id';

  insert into public.admin_audit_logs (
    actor_id,
    actor_email,
    action,
    table_name,
    row_id,
    details
  )
  values (
    auth.uid(),
    auth.jwt() ->> 'email',
    tg_op,
    tg_table_name,
    changed_id,
    jsonb_build_object(
      'old', case when tg_op in ('UPDATE', 'DELETE') then to_jsonb(old) else null end,
      'new', case when tg_op in ('INSERT', 'UPDATE') then to_jsonb(new) else null end
    )
  );

  if tg_op = 'DELETE' then
    return old;
  end if;

  return new;
end;
$$;

drop trigger if exists audit_clinicas_admin_changes on public.clinicas;
create trigger audit_clinicas_admin_changes
after insert or update or delete on public.clinicas
for each row execute function public.log_admin_change();

drop trigger if exists audit_forum_categories_admin_changes on public.forum_categories;
create trigger audit_forum_categories_admin_changes
after insert or update or delete on public.forum_categories
for each row execute function public.log_admin_change();

drop trigger if exists audit_forum_ads_admin_changes on public.forum_ads;
create trigger audit_forum_ads_admin_changes
after insert or update or delete on public.forum_ads
for each row execute function public.log_admin_change();
