create table if not exists public.forum_ads (
  id bigint generated by default as identity primary key,
  titulo text not null,
  descricao text,
  imagem text,
  link text,
  ativo boolean default true,
  ordem integer default 0,
  tipo text default 'clinica',
  created_at timestamptz default now()
);

alter table public.forum_ads
  add column if not exists descricao text,
  add column if not exists imagem text,
  add column if not exists link text,
  add column if not exists ativo boolean default true,
  add column if not exists ordem integer default 0,
  add column if not exists tipo text default 'clinica',
  add column if not exists created_at timestamptz default now();

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'forum_ads_tipo_check'
      and conrelid = 'public.forum_ads'::regclass
  ) then
    alter table public.forum_ads
      add constraint forum_ads_tipo_check
      check (tipo in ('clinica', 'modelo', 'campanha')) not valid;
  end if;
end $$;

create index if not exists forum_ads_ativo_ordem_created_at_idx
  on public.forum_ads(ativo, ordem, created_at desc);

create index if not exists forum_ads_tipo_idx
  on public.forum_ads(tipo);

alter table public.forum_ads enable row level security;

grant select on table public.forum_ads to anon, authenticated;

do $$
begin
  if exists (
    select 1
    from pg_class sequence_class
    join pg_namespace namespace
      on namespace.oid = sequence_class.relnamespace
    where sequence_class.relkind = 'S'
      and namespace.nspname = 'public'
      and sequence_class.relname = 'forum_ads_id_seq'
  ) then
    grant usage, select on sequence public.forum_ads_id_seq to anon, authenticated;
  end if;
end $$;

drop policy if exists "Active forum ads are readable" on public.forum_ads;
create policy "Active forum ads are readable"
on public.forum_ads
for select
to anon, authenticated
using (coalesce(ativo, false) = true);

comment on table public.forum_ads is 'Single premium monetization carousel for the forum. Future click tracking, campaign windows, and advertiser plan metadata should extend this placement instead of adding more ad slots.';
comment on column public.forum_ads.tipo is 'Allowed values: clinica, modelo, campanha.';
comment on column public.forum_ads.ordem is 'Lower values appear first in the forum hero carousel.';
