create extension if not exists unaccent with schema public;

create or replace function public.generate_slug(value text)
returns text
language sql
immutable
as $$
  select trim(both '-' from regexp_replace(lower(unaccent(coalesce(value, ''))), '[^a-z0-9]+', '-', 'g'));
$$;

alter table public.profiles
  add column if not exists user_id uuid references auth.users(id) on delete cascade,
  add column if not exists name text,
  add column if not exists email text,
  add column if not exists role text not null default 'user';

update public.profiles
set user_id = id
where user_id is null;

create unique index if not exists profiles_user_id_unique_idx
  on public.profiles(user_id)
  where user_id is not null;

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.cities (
  id bigint generated by default as identity primary key,
  name text not null,
  state text not null,
  slug text not null unique,
  latitude numeric,
  longitude numeric,
  created_at timestamptz not null default now()
);

create table if not exists public.ads (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  category_id bigint references public.categories(id),
  city_id bigint references public.cities(id),
  title text not null,
  slug text not null unique,
  description text,
  gender text,
  age integer,
  neighborhood text,
  latitude numeric,
  longitude numeric,
  price numeric,
  whatsapp text,
  phone text,
  status text not null default 'pending',
  is_verified boolean not null default false,
  is_premium boolean not null default false,
  is_featured boolean not null default false,
  available_now boolean not null default false,
  views_count integer not null default 0,
  whatsapp_clicks integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  expires_at timestamptz
);

create table if not exists public.ad_photos (
  id bigint generated by default as identity primary key,
  ad_id bigint not null references public.ads(id) on delete cascade,
  image_url text not null,
  thumbnail_url text,
  position integer not null default 0,
  is_verified boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.ad_videos (
  id bigint generated by default as identity primary key,
  ad_id bigint not null references public.ads(id) on delete cascade,
  video_url text not null,
  thumbnail_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.ad_audios (
  id bigint generated by default as identity primary key,
  ad_id bigint not null references public.ads(id) on delete cascade,
  audio_url text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.ad_services (
  id bigint generated by default as identity primary key,
  ad_id bigint not null references public.ads(id) on delete cascade,
  service_name text not null
);

create table if not exists public.ad_tags (
  id bigint generated by default as identity primary key,
  ad_id bigint not null references public.ads(id) on delete cascade,
  tag_name text not null
);

create table if not exists public.favorites (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  ad_id bigint not null references public.ads(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique(user_id, ad_id)
);

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  ad_id bigint not null references public.ads(id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,
  rating integer not null check (rating between 1 and 5),
  comment text,
  status text not null default 'pending',
  created_at timestamptz not null default now()
);

alter table public.reports
  add column if not exists ad_id bigint references public.ads(id) on delete cascade;

create table if not exists public.plans (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric not null default 0,
  duration_days integer not null default 30,
  features jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  ad_id bigint references public.ads(id) on delete set null,
  plan_id bigint references public.plans(id),
  amount numeric not null default 0,
  status text not null default 'pending',
  payment_method text,
  external_payment_id text,
  created_at timestamptz not null default now()
);

create table if not exists public.boosts (
  id bigint generated by default as identity primary key,
  ad_id bigint not null references public.ads(id) on delete cascade,
  type text not null,
  starts_at timestamptz,
  ends_at timestamptz,
  status text not null default 'scheduled',
  created_at timestamptz not null default now()
);

create table if not exists public.legal_acceptances (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  terms_version text not null,
  accepted_at timestamptz not null default now(),
  ip_address text
);

create table if not exists public.age_verifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'pending',
  provider text,
  verified_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.admin_logs (
  id bigint generated by default as identity primary key,
  admin_id uuid references auth.users(id) on delete set null,
  action text not null,
  target_type text not null,
  target_id text,
  created_at timestamptz not null default now()
);

alter table public.ads
  add constraint ads_status_check
  check (status in ('pending', 'approved', 'rejected', 'suspended', 'expired')) not valid;

alter table public.reviews
  add constraint reviews_status_check
  check (status in ('pending', 'approved', 'rejected', 'hidden')) not valid;

create index if not exists ads_status_created_at_idx on public.ads(status, created_at desc);
create index if not exists ads_city_id_idx on public.ads(city_id);
create index if not exists ads_category_id_idx on public.ads(category_id);
create index if not exists ads_user_id_idx on public.ads(user_id);
create index if not exists ads_premium_featured_idx on public.ads(is_premium, is_featured);
create index if not exists ad_photos_ad_id_position_idx on public.ad_photos(ad_id, position);
create index if not exists ad_videos_ad_id_idx on public.ad_videos(ad_id);
create index if not exists ad_audios_ad_id_idx on public.ad_audios(ad_id);
create index if not exists ad_services_ad_id_idx on public.ad_services(ad_id);
create index if not exists ad_tags_ad_id_idx on public.ad_tags(ad_id);
create index if not exists favorites_user_id_idx on public.favorites(user_id);
create index if not exists favorites_ad_id_idx on public.favorites(ad_id);
create index if not exists reviews_ad_id_status_idx on public.reviews(ad_id, status);
create index if not exists reports_ad_id_status_idx on public.reports(ad_id, status);
create index if not exists payments_user_id_idx on public.payments(user_id);
create index if not exists payments_ad_id_idx on public.payments(ad_id);
create index if not exists boosts_ad_id_status_idx on public.boosts(ad_id, status);
create index if not exists legal_acceptances_user_id_idx on public.legal_acceptances(user_id);
create index if not exists age_verifications_user_id_idx on public.age_verifications(user_id);
create index if not exists admin_logs_created_at_idx on public.admin_logs(created_at desc);

alter table public.categories enable row level security;
alter table public.cities enable row level security;
alter table public.ads enable row level security;
alter table public.ad_photos enable row level security;
alter table public.ad_videos enable row level security;
alter table public.ad_audios enable row level security;
alter table public.ad_services enable row level security;
alter table public.ad_tags enable row level security;
alter table public.favorites enable row level security;
alter table public.reviews enable row level security;
alter table public.reports enable row level security;
alter table public.plans enable row level security;
alter table public.payments enable row level security;
alter table public.boosts enable row level security;
alter table public.legal_acceptances enable row level security;
alter table public.age_verifications enable row level security;
alter table public.admin_logs enable row level security;

grant select on table public.categories, public.cities, public.plans to anon, authenticated;
grant select on table public.ads, public.ad_photos, public.ad_videos, public.ad_audios, public.ad_services, public.ad_tags, public.reviews, public.boosts to anon, authenticated;
grant insert on table public.reports to anon, authenticated;
grant insert, update, delete on table public.ads, public.ad_photos, public.ad_videos, public.ad_audios, public.ad_services, public.ad_tags, public.favorites, public.reviews, public.payments, public.legal_acceptances, public.age_verifications to authenticated;
grant select on table public.favorites, public.payments, public.legal_acceptances, public.age_verifications to authenticated;
grant select, insert on table public.admin_logs to authenticated;

grant usage, select on all sequences in schema public to authenticated;

drop policy if exists "Read categories" on public.categories;
create policy "Read categories" on public.categories for select to anon, authenticated using (true);

drop policy if exists "Read cities" on public.cities;
create policy "Read cities" on public.cities for select to anon, authenticated using (true);

drop policy if exists "Read plans" on public.plans;
create policy "Read plans" on public.plans for select to anon, authenticated using (true);

drop policy if exists "Read approved ads" on public.ads;
create policy "Read approved ads" on public.ads for select to anon, authenticated
using (status = 'approved' or user_id = auth.uid() or public.is_admin());

drop policy if exists "Users insert own pending ads" on public.ads;
create policy "Users insert own pending ads" on public.ads for insert to authenticated
with check (user_id = auth.uid() and status = 'pending');

drop policy if exists "Users update own ads" on public.ads;
create policy "Users update own ads" on public.ads for update to authenticated
using (user_id = auth.uid() or public.is_admin())
with check (user_id = auth.uid() or public.is_admin());

drop policy if exists "Users delete own ads" on public.ads;
create policy "Users delete own ads" on public.ads for delete to authenticated
using (user_id = auth.uid() or public.is_admin());

drop policy if exists "Read ad media for visible ads" on public.ad_photos;
create policy "Read ad media for visible ads" on public.ad_photos for select to anon, authenticated
using (exists (select 1 from public.ads where ads.id = ad_photos.ad_id and (ads.status = 'approved' or ads.user_id = auth.uid() or public.is_admin())));

drop policy if exists "Manage own ad photos" on public.ad_photos;
create policy "Manage own ad photos" on public.ad_photos for all to authenticated
using (exists (select 1 from public.ads where ads.id = ad_photos.ad_id and (ads.user_id = auth.uid() or public.is_admin())))
with check (exists (select 1 from public.ads where ads.id = ad_photos.ad_id and (ads.user_id = auth.uid() or public.is_admin())));

drop policy if exists "Read ad videos for visible ads" on public.ad_videos;
create policy "Read ad videos for visible ads" on public.ad_videos for select to anon, authenticated
using (exists (select 1 from public.ads where ads.id = ad_videos.ad_id and (ads.status = 'approved' or ads.user_id = auth.uid() or public.is_admin())));

drop policy if exists "Manage own ad videos" on public.ad_videos;
create policy "Manage own ad videos" on public.ad_videos for all to authenticated
using (exists (select 1 from public.ads where ads.id = ad_videos.ad_id and (ads.user_id = auth.uid() or public.is_admin())))
with check (exists (select 1 from public.ads where ads.id = ad_videos.ad_id and (ads.user_id = auth.uid() or public.is_admin())));

drop policy if exists "Read ad audios for visible ads" on public.ad_audios;
create policy "Read ad audios for visible ads" on public.ad_audios for select to anon, authenticated
using (exists (select 1 from public.ads where ads.id = ad_audios.ad_id and (ads.status = 'approved' or ads.user_id = auth.uid() or public.is_admin())));

drop policy if exists "Manage own ad audios" on public.ad_audios;
create policy "Manage own ad audios" on public.ad_audios for all to authenticated
using (exists (select 1 from public.ads where ads.id = ad_audios.ad_id and (ads.user_id = auth.uid() or public.is_admin())))
with check (exists (select 1 from public.ads where ads.id = ad_audios.ad_id and (ads.user_id = auth.uid() or public.is_admin())));

drop policy if exists "Read ad services" on public.ad_services;
create policy "Read ad services" on public.ad_services for select to anon, authenticated
using (exists (select 1 from public.ads where ads.id = ad_services.ad_id and (ads.status = 'approved' or ads.user_id = auth.uid() or public.is_admin())));

drop policy if exists "Manage own ad services" on public.ad_services;
create policy "Manage own ad services" on public.ad_services for all to authenticated
using (exists (select 1 from public.ads where ads.id = ad_services.ad_id and (ads.user_id = auth.uid() or public.is_admin())))
with check (exists (select 1 from public.ads where ads.id = ad_services.ad_id and (ads.user_id = auth.uid() or public.is_admin())));

drop policy if exists "Read ad tags" on public.ad_tags;
create policy "Read ad tags" on public.ad_tags for select to anon, authenticated
using (exists (select 1 from public.ads where ads.id = ad_tags.ad_id and (ads.status = 'approved' or ads.user_id = auth.uid() or public.is_admin())));

drop policy if exists "Manage own ad tags" on public.ad_tags;
create policy "Manage own ad tags" on public.ad_tags for all to authenticated
using (exists (select 1 from public.ads where ads.id = ad_tags.ad_id and (ads.user_id = auth.uid() or public.is_admin())))
with check (exists (select 1 from public.ads where ads.id = ad_tags.ad_id and (ads.user_id = auth.uid() or public.is_admin())));

drop policy if exists "Users manage own favorites" on public.favorites;
create policy "Users manage own favorites" on public.favorites for all to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists "Read approved reviews" on public.reviews;
create policy "Read approved reviews" on public.reviews for select to anon, authenticated
using (status = 'approved' or public.is_admin());

drop policy if exists "Users create reviews" on public.reviews;
create policy "Users create reviews" on public.reviews for insert to authenticated
with check (status = 'pending');

drop policy if exists "Admins manage reviews" on public.reviews;
create policy "Admins manage reviews" on public.reviews for all to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Anyone can report club ads" on public.reports;
create policy "Anyone can report club ads" on public.reports for insert to anon, authenticated
with check (coalesce(product, 'club') in ('club', 'forum', 'lounge'));

drop policy if exists "Admins read reports" on public.reports;
create policy "Admins read reports" on public.reports for select to authenticated
using (public.is_admin());

drop policy if exists "Users read own payments" on public.payments;
create policy "Users read own payments" on public.payments for select to authenticated
using (user_id = auth.uid() or public.is_admin());

drop policy if exists "Users create own pending payments" on public.payments;
create policy "Users create own pending payments" on public.payments for insert to authenticated
with check (user_id = auth.uid());

drop policy if exists "Read active boosts" on public.boosts;
create policy "Read active boosts" on public.boosts for select to anon, authenticated
using (status = 'active' or public.is_admin());

drop policy if exists "Users read own legal acceptances" on public.legal_acceptances;
create policy "Users read own legal acceptances" on public.legal_acceptances for select to authenticated
using (user_id = auth.uid() or public.is_admin());

drop policy if exists "Users create own legal acceptances" on public.legal_acceptances;
create policy "Users create own legal acceptances" on public.legal_acceptances for insert to authenticated
with check (user_id = auth.uid());

drop policy if exists "Users read own age verifications" on public.age_verifications;
create policy "Users read own age verifications" on public.age_verifications for select to authenticated
using (user_id = auth.uid() or public.is_admin());

drop policy if exists "Users create own age verification" on public.age_verifications;
create policy "Users create own age verification" on public.age_verifications for insert to authenticated
with check (user_id = auth.uid());

drop policy if exists "Admins read admin logs" on public.admin_logs;
create policy "Admins read admin logs" on public.admin_logs for select to authenticated
using (public.is_admin());

drop policy if exists "Admins create admin logs" on public.admin_logs;
create policy "Admins create admin logs" on public.admin_logs for insert to authenticated
with check (public.is_admin());

insert into public.categories (name, slug)
values
  ('Acompanhantes', 'acompanhantes'),
  ('Massagens', 'massagens'),
  ('Encontros Premium', 'encontros-premium'),
  ('Experiencias', 'experiencias')
on conflict (slug) do update set name = excluded.name;

insert into public.cities (name, state, slug, latitude, longitude)
values
  ('Sao Paulo', 'SP', 'sao-paulo', -23.5505, -46.6333),
  ('Rio de Janeiro', 'RJ', 'rio-de-janeiro', -22.9068, -43.1729),
  ('Belo Horizonte', 'MG', 'belo-horizonte', -19.9167, -43.9345),
  ('Curitiba', 'PR', 'curitiba', -25.4284, -49.2733),
  ('Florianopolis', 'SC', 'florianopolis', -27.5949, -48.5482),
  ('Porto Alegre', 'RS', 'porto-alegre', -30.0346, -51.2177)
on conflict (slug) do update
set name = excluded.name,
    state = excluded.state,
    latitude = excluded.latitude,
    longitude = excluded.longitude;

insert into public.plans (name, price, duration_days, features)
values
  ('Basico', 49.90, 30, '["Pagina do anuncio","Ate 4 fotos","WhatsApp","Listagem padrao"]'::jsonb),
  ('Premium', 89.90, 30, '["Tudo do Basico","Selo Premium","Ate 10 fotos","Prioridade por cidade"]'::jsonb),
  ('Destaque', 129.90, 30, '["Tudo do Premium","Carrossel principal","Relatorio de cliques","Mais destaque nos filtros"]'::jsonb),
  ('Turbo', 199.90, 30, '["Tudo do Destaque","Prioridade maxima","Campanha especial","Suporte de publicacao"]'::jsonb);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values
  ('ad-photos', 'ad-photos', true, 10485760, array['image/jpeg','image/png','image/webp']),
  ('ad-videos', 'ad-videos', false, 104857600, array['video/mp4','video/webm']),
  ('ad-audios', 'ad-audios', false, 20971520, array['audio/mpeg','audio/mp4','audio/webm','audio/wav'])
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Public read ad photos" on storage.objects;
create policy "Public read ad photos" on storage.objects for select to anon, authenticated
using (bucket_id = 'ad-photos');

drop policy if exists "Users upload own ad media" on storage.objects;
create policy "Users upload own ad media" on storage.objects for insert to authenticated
with check (
  bucket_id in ('ad-photos', 'ad-videos', 'ad-audios')
  and (storage.foldername(name))[1] = auth.uid()::text
);

drop policy if exists "Users manage own ad media" on storage.objects;
create policy "Users manage own ad media" on storage.objects for update to authenticated
using (
  bucket_id in ('ad-photos', 'ad-videos', 'ad-audios')
  and (storage.foldername(name))[1] = auth.uid()::text
)
with check (
  bucket_id in ('ad-photos', 'ad-videos', 'ad-audios')
  and (storage.foldername(name))[1] = auth.uid()::text
);

drop policy if exists "Users delete own ad media" on storage.objects;
create policy "Users delete own ad media" on storage.objects for delete to authenticated
using (
  bucket_id in ('ad-photos', 'ad-videos', 'ad-audios')
  and ((storage.foldername(name))[1] = auth.uid()::text or public.is_admin())
);
