alter table public.plans
  add column if not exists slug text,
  add column if not exists billing_period text default 'monthly',
  add column if not exists tier integer not null default 0,
  add column if not exists max_photos integer not null default 4,
  add column if not exists max_videos integer not null default 0,
  add column if not exists max_stories integer not null default 0,
  add column if not exists sorting_weight integer not null default 0,
  add column if not exists is_active boolean not null default true;

create unique index if not exists plans_slug_billing_period_unique_idx
  on public.plans(slug, billing_period);

create index if not exists plans_active_tier_idx
  on public.plans(is_active, tier desc);

alter table public.payments
  add column if not exists plan_slug text,
  add column if not exists billing_period text,
  add column if not exists external_reference text,
  add column if not exists external_preference_id text,
  add column if not exists checkout_url text,
  add column if not exists expires_at timestamptz,
  add column if not exists paid_at timestamptz,
  add column if not exists raw_payload jsonb;

create unique index if not exists payments_external_reference_unique_idx
  on public.payments(external_reference);

create index if not exists payments_external_payment_id_idx
  on public.payments(external_payment_id)
  where external_payment_id is not null;

alter table public.ads
  add column if not exists plan_status text not null default 'free',
  add column if not exists plan_expires_at timestamptz,
  add column if not exists sorting_weight integer not null default 0;

create index if not exists ads_sorting_weight_created_idx
  on public.ads(sorting_weight desc, created_at desc);

create table if not exists public.club_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  plan_slug text not null,
  billing_period text not null,
  status text not null default 'pending',
  starts_at timestamptz,
  current_period_end timestamptz,
  canceled_at timestamptz,
  external_reference text,
  external_payment_id text,
  external_preference_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint club_subscriptions_plan_slug_check
    check (plan_slug in ('basico', 'premium')),
  constraint club_subscriptions_billing_period_check
    check (billing_period in ('weekly', 'monthly')),
  constraint club_subscriptions_status_check
    check (status in ('pending', 'active', 'past_due', 'canceled', 'expired'))
);

create index if not exists club_subscriptions_user_status_period_idx
  on public.club_subscriptions(user_id, status, current_period_end desc);

create unique index if not exists club_subscriptions_external_reference_unique_idx
  on public.club_subscriptions(external_reference);

alter table public.club_subscriptions enable row level security;

grant select on table public.club_subscriptions to authenticated;
grant all on table public.club_subscriptions to service_role;
grant usage, select on sequence public.club_subscriptions_id_seq to authenticated, service_role;

drop policy if exists "Users read own club subscriptions" on public.club_subscriptions;
create policy "Users read own club subscriptions"
on public.club_subscriptions
for select
to authenticated
using (user_id = auth.uid() or public.is_admin());

drop policy if exists "Admins manage club subscriptions" on public.club_subscriptions;
create policy "Admins manage club subscriptions"
on public.club_subscriptions
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

insert into public.plans (
  name,
  slug,
  billing_period,
  price,
  duration_days,
  tier,
  max_photos,
  max_videos,
  max_stories,
  sorting_weight,
  features,
  is_active
)
values
  (
    'Gratuito',
    'free',
    'free',
    0,
    0,
    0,
    4,
    0,
    0,
    0,
    '["4 fotos", "Sem video", "Sem stories", "Aprovacao manual", "Fluxo gratuito"]'::jsonb,
    true
  ),
  (
    'Basico semanal',
    'basico',
    'weekly',
    29.90,
    7,
    10,
    6,
    3,
    0,
    10,
    '["6 fotos", "3 videos de ate 10 segundos", "Acima dos gratuitos", "Aprovacao manual"]'::jsonb,
    true
  ),
  (
    'Basico mensal',
    'basico',
    'monthly',
    99.90,
    30,
    10,
    6,
    3,
    0,
    10,
    '["6 fotos", "3 videos de ate 10 segundos", "Acima dos gratuitos", "Aprovacao manual"]'::jsonb,
    true
  ),
  (
    'Premium semanal',
    'premium',
    'weekly',
    69.90,
    7,
    20,
    6,
    3,
    1,
    20,
    '["Tudo do Basico", "1 story como capa", "Acima dos Basicos", "Selo Premium", "Aprovacao manual"]'::jsonb,
    true
  ),
  (
    'Premium mensal',
    'premium',
    'monthly',
    199.90,
    30,
    20,
    6,
    3,
    1,
    20,
    '["Tudo do Basico", "1 story como capa", "Acima dos Basicos", "Selo Premium", "Aprovacao manual"]'::jsonb,
    true
  )
on conflict (slug, billing_period) do update
set
  name = excluded.name,
  price = excluded.price,
  duration_days = excluded.duration_days,
  tier = excluded.tier,
  max_photos = excluded.max_photos,
  max_videos = excluded.max_videos,
  max_stories = excluded.max_stories,
  sorting_weight = excluded.sorting_weight,
  features = excluded.features,
  is_active = excluded.is_active;

create or replace function public.club_plan_limit(plan_name text, metric text)
returns integer
language sql
immutable
set search_path = public
as $$
  select case lower(coalesce(metric, ''))
    when 'photos' then
      case lower(coalesce(plan_name, 'free'))
        when 'premium' then 6
        when 'basico' then 6
        else 4
      end
    when 'videos' then
      case lower(coalesce(plan_name, 'free'))
        when 'premium' then 3
        when 'basico' then 3
        else 0
      end
    when 'stories' then
      case lower(coalesce(plan_name, 'free'))
        when 'premium' then 1
        else 0
      end
    else 0
  end;
$$;

grant execute on function public.club_plan_limit(text, text) to anon, authenticated;

create or replace function public.enforce_club_plan_access()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  requested_plan text := lower(coalesce(new.plan_slug, 'free'));
  active_subscription record;
begin
  if requested_plan not in ('free', 'basico', 'premium') then
    raise exception 'Plano invalido para anuncio.';
  end if;

  if requested_plan = 'free' then
    new.plan_slug := 'free';
    new.plan_status := 'free';
    new.plan_expires_at := null;
    new.sorting_weight := 0;
    new.is_premium := false;
    new.is_featured := false;
    new.stories_enabled := false;
    new.stories_count := 0;
    return new;
  end if;

  if not public.is_admin() then
    select subscription.plan_slug,
           subscription.billing_period,
           subscription.current_period_end
      into active_subscription
      from public.club_subscriptions subscription
      where subscription.user_id = new.user_id
        and subscription.plan_slug = requested_plan
        and subscription.status = 'active'
        and subscription.current_period_end > now()
      order by subscription.current_period_end desc
      limit 1;

    if not found then
      raise exception 'Plano pago ainda nao confirmado.';
    end if;

    new.plan_expires_at := active_subscription.current_period_end;
  end if;

  new.plan_status := 'active';
  new.sorting_weight := case requested_plan
    when 'premium' then 20
    when 'basico' then 10
    else 0
  end;
  new.is_premium := requested_plan = 'premium';
  new.is_featured := false;

  if requested_plan <> 'premium' then
    new.stories_enabled := false;
    new.stories_count := 0;
  elsif coalesce(new.stories_count, 0) > 1 then
    raise exception 'Plano Premium permite no maximo 1 story.';
  end if;

  return new;
end;
$$;

update public.ads
set
  plan_slug = case
    when is_premium then 'premium'
    when coalesce(plan_slug, '') in ('basico', 'premium', 'free') then plan_slug
    else 'free'
  end,
  plan_status = case
    when coalesce(plan_slug, 'free') = 'free' then 'free'
    else coalesce(plan_status, 'active')
  end,
  sorting_weight = case
    when is_premium or coalesce(plan_slug, '') = 'premium' then 20
    when coalesce(plan_slug, '') = 'basico' then 10
    else 0
  end;

drop trigger if exists enforce_club_plan_access on public.ads;
create trigger enforce_club_plan_access
before insert or update of plan_slug, stories_enabled, stories_count, user_id on public.ads
for each row execute function public.enforce_club_plan_access();

create or replace function public.enforce_club_media_limits()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  media_count integer;
  owner_plan text;
  allowed_count integer;
begin
  select coalesce(ad.plan_slug, 'free')
    into owner_plan
    from public.ads ad
    where ad.id = new.ad_id;

  owner_plan := coalesce(owner_plan, 'free');

  if tg_table_name = 'ad_photos' then
    allowed_count := public.club_plan_limit(owner_plan, 'photos');

    select count(*)
      into media_count
      from public.ad_photos
      where ad_id = new.ad_id
        and id is distinct from new.id;

    if media_count >= allowed_count then
      raise exception 'Este plano permite no maximo % fotos.', allowed_count;
    end if;
  elsif tg_table_name = 'ad_videos' then
    allowed_count := public.club_plan_limit(owner_plan, 'videos');

    if allowed_count <= 0 then
      raise exception 'Este plano nao permite videos.';
    end if;

    if new.duration_seconds is not null and new.duration_seconds > 10 then
      raise exception 'Cada video pode ter no maximo 10 segundos.';
    end if;

    select count(*)
      into media_count
      from public.ad_videos
      where ad_id = new.ad_id
        and id is distinct from new.id;

    if media_count >= allowed_count then
      raise exception 'Este plano permite no maximo % videos.', allowed_count;
    end if;
  elsif tg_table_name = 'ad_audios' then
    if new.duration_seconds is not null and new.duration_seconds > 8 then
      raise exception 'O audio pode ter no maximo 8 segundos.';
    end if;

    select count(*)
      into media_count
      from public.ad_audios
      where ad_id = new.ad_id
        and id is distinct from new.id;

    if media_count >= 1 then
      raise exception 'Cada anuncio pode ter no maximo 1 audio.';
    end if;
  end if;

  return new;
end;
$$;
