create table if not exists public.forum_categories (
  id bigint generated by default as identity primary key,
  nome text not null,
  slug text not null unique,
  descricao text,
  parent_id bigint references public.forum_categories(id),
  estado text,
  tipo text,
  clinic_id bigint references public.clinicas(id),
  created_at timestamptz default now()
);

create table if not exists public.forum_topics (
  id bigint generated by default as identity primary key,
  category_id bigint references public.forum_categories(id),
  clinic_id bigint references public.clinicas(id),
  titulo text not null,
  slug text not null unique,
  conteudo text not null,
  autor text default 'Anônimo',
  user_id uuid references auth.users(id),
  nota numeric,
  views integer default 0,
  pinned boolean default false,
  locked boolean default false,
  fixado boolean default false,
  trancado boolean default false,
  oculto boolean default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  constraint forum_topics_nota_range check (nota is null or (nota >= 1 and nota <= 5))
);

create table if not exists public.forum_replies (
  id bigint generated by default as identity primary key,
  topic_id bigint references public.forum_topics(id),
  conteudo text not null,
  autor text default 'Anônimo',
  user_id uuid references auth.users(id),
  oculto boolean default false,
  created_at timestamptz default now()
);

alter table public.forum_categories
  add column if not exists estado text,
  add column if not exists tipo text,
  add column if not exists clinic_id bigint references public.clinicas(id);

alter table public.forum_topics
  add column if not exists clinic_id bigint references public.clinicas(id),
  add column if not exists autor text default 'Anônimo',
  add column if not exists nota numeric,
  add column if not exists fixado boolean default false,
  add column if not exists trancado boolean default false,
  add column if not exists oculto boolean default false,
  add column if not exists updated_at timestamptz default now();

alter table public.forum_replies
  add column if not exists autor text default 'Anônimo',
  add column if not exists oculto boolean default false;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'forum_topics_nota_range'
      and conrelid = 'public.forum_topics'::regclass
  ) then
    alter table public.forum_topics
      add constraint forum_topics_nota_range
      check (nota is null or (nota >= 1 and nota <= 5));
  end if;
end $$;

create index if not exists forum_categories_parent_id_idx
  on public.forum_categories(parent_id);

create index if not exists forum_categories_estado_tipo_idx
  on public.forum_categories(estado, tipo);

create index if not exists forum_categories_clinic_id_idx
  on public.forum_categories(clinic_id);

create index if not exists forum_topics_category_id_idx
  on public.forum_topics(category_id);

create index if not exists forum_topics_clinic_id_idx
  on public.forum_topics(clinic_id);

create index if not exists forum_topics_created_at_idx
  on public.forum_topics(created_at desc);

create index if not exists forum_topics_oculto_idx
  on public.forum_topics(oculto);

create index if not exists forum_replies_topic_id_idx
  on public.forum_replies(topic_id);

create index if not exists forum_replies_created_at_idx
  on public.forum_replies(created_at desc);

create index if not exists forum_replies_oculto_idx
  on public.forum_replies(oculto);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_forum_topics_updated_at on public.forum_topics;
create trigger set_forum_topics_updated_at
before update on public.forum_topics
for each row execute function public.set_updated_at();

insert into public.forum_categories (nome, slug, descricao, estado)
values
  ('São Paulo', 'sao-paulo', 'Discussões e avaliações em São Paulo.', 'SP'),
  ('Minas Gerais', 'minas-gerais', 'Discussões e avaliações em Minas Gerais.', 'MG'),
  ('Rio de Janeiro', 'rio-de-janeiro', 'Discussões e avaliações no Rio de Janeiro.', 'RJ'),
  ('Paraná', 'parana', 'Discussões e avaliações no Paraná.', 'PR'),
  ('Santa Catarina', 'santa-catarina', 'Discussões e avaliações em Santa Catarina.', 'SC'),
  ('Rio Grande do Sul', 'rio-grande-do-sul', 'Discussões e avaliações no Rio Grande do Sul.', 'RS')
on conflict (slug) do update
set descricao = excluded.descricao,
    estado = excluded.estado;

with states as (
  select id, estado
  from public.forum_categories
  where parent_id is null
    and estado in ('SP', 'MG', 'RJ', 'PR', 'SC', 'RS')
),
kinds as (
  select *
  from (values
    ('clinica', 'Clínicas', 'clinicas'),
    ('massagem', 'Massagens', 'massagens'),
    ('boate', 'Boates', 'boates'),
    ('prive', 'Privês', 'prives')
  ) as kind(tipo, nome, slug_part)
)
insert into public.forum_categories (nome, slug, descricao, parent_id, estado, tipo)
select
  kinds.nome,
  lower(states.estado) || '-' || kinds.slug_part,
  kinds.nome || ' em ' || states.estado,
  states.id,
  states.estado,
  kinds.tipo
from states
cross join kinds
on conflict (slug) do update
set parent_id = excluded.parent_id,
    estado = excluded.estado,
    tipo = excluded.tipo;

with clinic_rows as (
  select
    id,
    nome,
    estado,
    tipo,
    regexp_replace(
      regexp_replace(
        translate(
          lower(coalesce(nome, 'local')),
          'áàâãäéèêëíìîïóòôõöúùûüçñ',
          'aaaaaeeeeiiiiooooouuuucn'
        ),
        '[^a-z0-9]+',
        '-',
        'g'
      ),
      '(^-|-$)',
      '',
      'g'
    ) as slug_nome
  from public.clinicas
  where estado in ('SP', 'MG', 'RJ', 'PR', 'SC', 'RS')
    and tipo in ('clinica', 'massagem', 'boate', 'prive')
),
parents as (
  select id, estado, tipo
  from public.forum_categories
  where parent_id is not null
    and clinic_id is null
),
inserted_categories as (
  insert into public.forum_categories (
    nome,
    slug,
    descricao,
    parent_id,
    clinic_id,
    estado,
    tipo
  )
  select
    clinic_rows.nome,
    clinic_rows.tipo || '-' || clinic_rows.id || '-' || coalesce(nullif(clinic_rows.slug_nome, ''), 'local'),
    'Discussões e avaliações sobre ' || clinic_rows.nome,
    parents.id,
    clinic_rows.id,
    clinic_rows.estado,
    clinic_rows.tipo
  from clinic_rows
  join parents
    on parents.estado = clinic_rows.estado
   and parents.tipo = clinic_rows.tipo
  on conflict (slug) do update
  set nome = excluded.nome,
      descricao = excluded.descricao,
      parent_id = excluded.parent_id,
      clinic_id = excluded.clinic_id,
      estado = excluded.estado,
      tipo = excluded.tipo
  returning id, clinic_id
)
update public.clinicas
set forum = '/forum/categoria/' || inserted_categories.id
from inserted_categories
where public.clinicas.id = inserted_categories.clinic_id;

update public.forum_topics
set clinic_id = forum_categories.clinic_id
from public.forum_categories
where public.forum_topics.category_id = forum_categories.id
  and public.forum_topics.clinic_id is null
  and forum_categories.clinic_id is not null;

alter table public.forum_categories enable row level security;
alter table public.forum_topics enable row level security;
alter table public.forum_replies enable row level security;

grant select on table public.forum_categories to anon, authenticated;
grant insert, update on table public.forum_categories to authenticated;
grant select, insert on table public.forum_topics to anon, authenticated;
grant select, insert on table public.forum_replies to anon, authenticated;

grant usage, select on sequence public.forum_categories_id_seq to anon, authenticated;
grant usage, select on sequence public.forum_topics_id_seq to anon, authenticated;
grant usage, select on sequence public.forum_replies_id_seq to anon, authenticated;

drop policy if exists "Forum categories are readable" on public.forum_categories;
create policy "Forum categories are readable"
on public.forum_categories
for select
to anon, authenticated
using (true);

drop policy if exists "Authenticated users can insert forum categories" on public.forum_categories;
create policy "Authenticated users can insert forum categories"
on public.forum_categories
for insert
to authenticated
with check (true);

drop policy if exists "Authenticated users can update forum categories" on public.forum_categories;
create policy "Authenticated users can update forum categories"
on public.forum_categories
for update
to authenticated
using (true)
with check (true);

drop policy if exists "Forum topics are readable" on public.forum_topics;
create policy "Forum topics are readable"
on public.forum_topics
for select
to anon, authenticated
using (coalesce(oculto, false) = false);

drop policy if exists "Anyone can create visible topics" on public.forum_topics;
create policy "Anyone can create visible topics"
on public.forum_topics
for insert
to anon, authenticated
with check (
  category_id is not null
  and length(btrim(titulo)) > 0
  and length(btrim(conteudo)) > 0
  and (nota is null or (nota >= 1 and nota <= 5))
  and coalesce(oculto, false) = false
  and coalesce(fixado, false) = false
  and coalesce(trancado, false) = false
  and (user_id is null or (select auth.uid()) = user_id)
);

drop policy if exists "Forum replies are readable" on public.forum_replies;
create policy "Forum replies are readable"
on public.forum_replies
for select
to anon, authenticated
using (coalesce(oculto, false) = false);

drop policy if exists "Anyone can create visible replies" on public.forum_replies;
create policy "Anyone can create visible replies"
on public.forum_replies
for insert
to anon, authenticated
with check (
  topic_id is not null
  and length(btrim(conteudo)) > 0
  and coalesce(oculto, false) = false
  and (user_id is null or (select auth.uid()) = user_id)
  and exists (
    select 1
    from public.forum_topics topic
    where topic.id = forum_replies.topic_id
      and coalesce(topic.oculto, false) = false
      and coalesce(topic.trancado, false) = false
  )
);
