create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  product text not null,
  target_type text not null,
  target_id bigint not null,
  reason text not null,
  description text,
  status text not null default 'open',
  created_at timestamptz default now()
);

alter table public.reports
  add column if not exists product text not null default 'forum',
  add column if not exists target_type text not null default 'topic',
  add column if not exists target_id bigint not null default 0,
  add column if not exists reason text not null default 'other',
  add column if not exists description text,
  add column if not exists status text not null default 'open',
  add column if not exists created_at timestamptz default now();

create table if not exists public.banner_ads (
  id bigint generated by default as identity primary key,
  product text not null default 'forum',
  title text not null,
  image_url text,
  link_url text,
  starts_at timestamptz,
  ends_at timestamptz,
  status text not null default 'draft',
  created_at timestamptz default now()
);

alter table public.banner_ads
  add column if not exists product text not null default 'forum',
  add column if not exists title text not null default 'Espaço PrivacyLog',
  add column if not exists image_url text,
  add column if not exists link_url text,
  add column if not exists starts_at timestamptz,
  add column if not exists ends_at timestamptz,
  add column if not exists status text not null default 'draft',
  add column if not exists created_at timestamptz default now();

create index if not exists reports_product_status_created_at_idx
  on public.reports(product, status, created_at desc);

create index if not exists reports_target_idx
  on public.reports(product, target_type, target_id);

create index if not exists banner_ads_product_status_created_at_idx
  on public.banner_ads(product, status, created_at desc);

alter table public.reports enable row level security;
alter table public.banner_ads enable row level security;

grant insert on table public.reports to authenticated;
grant select on table public.banner_ads to anon, authenticated;

grant usage, select on sequence public.reports_id_seq to authenticated;

drop policy if exists "Users can create reports" on public.reports;
create policy "Users can create reports"
on public.reports
for insert
to authenticated
with check (true);

drop policy if exists "Active banner ads are readable" on public.banner_ads;
create policy "Active banner ads are readable"
on public.banner_ads
for select
to anon, authenticated
using (
  status = 'active'
  and (starts_at is null or starts_at <= now())
  and (ends_at is null or ends_at >= now())
);
