alter table public.forum_replies
  add column if not exists td_type text default 'comentario',
  add column if not exists model_name text,
  add column if not exists amount_paid numeric,
  add column if not exists time_with_gp_minutes integer,
  add column if not exists oral_without_condom boolean,
  add column if not exists anal boolean,
  add column if not exists kissed boolean,
  add column if not exists service_score integer;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'forum_replies_td_type_check'
      and conrelid = 'public.forum_replies'::regclass
  ) then
    alter table public.forum_replies
      add constraint forum_replies_td_type_check
      check (
        td_type is null
        or td_type in ('comentario', 'neutro', 'positivo', 'negativo', 'pisou_na_bola')
      );
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'forum_replies_amount_paid_check'
      and conrelid = 'public.forum_replies'::regclass
  ) then
    alter table public.forum_replies
      add constraint forum_replies_amount_paid_check
      check (amount_paid is null or amount_paid >= 0);
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'forum_replies_time_with_gp_check'
      and conrelid = 'public.forum_replies'::regclass
  ) then
    alter table public.forum_replies
      add constraint forum_replies_time_with_gp_check
      check (time_with_gp_minutes is null or time_with_gp_minutes > 0);
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'forum_replies_service_score_check'
      and conrelid = 'public.forum_replies'::regclass
  ) then
    alter table public.forum_replies
      add constraint forum_replies_service_score_check
      check (service_score is null or (service_score >= 0 and service_score <= 10));
  end if;
end $$;

create table if not exists public.forum_clinic_models (
  id bigint generated by default as identity primary key,
  clinic_id bigint references public.clinicas(id) on delete cascade,
  category_id bigint references public.forum_categories(id) on delete cascade,
  name text not null,
  active boolean default true,
  sort_order integer default 0,
  created_at timestamptz default now(),
  constraint forum_clinic_models_scope_check
    check (clinic_id is not null or category_id is not null)
);

create index if not exists forum_clinic_models_clinic_id_idx
  on public.forum_clinic_models(clinic_id);

create index if not exists forum_clinic_models_category_id_idx
  on public.forum_clinic_models(category_id);

create unique index if not exists forum_clinic_models_clinic_name_unique
  on public.forum_clinic_models(clinic_id, lower(name))
  where clinic_id is not null;

create unique index if not exists forum_clinic_models_category_name_unique
  on public.forum_clinic_models(category_id, lower(name))
  where category_id is not null;

alter table public.forum_clinic_models enable row level security;

grant select on table public.forum_clinic_models to anon, authenticated;
grant insert, update, delete on table public.forum_clinic_models to authenticated;
grant usage, select on sequence public.forum_clinic_models_id_seq to authenticated;

drop policy if exists "Forum clinic models are readable" on public.forum_clinic_models;
create policy "Forum clinic models are readable"
on public.forum_clinic_models
for select
to anon, authenticated
using (coalesce(active, true) = true);

drop policy if exists "Authenticated users can manage forum clinic models" on public.forum_clinic_models;
create policy "Authenticated users can manage forum clinic models"
on public.forum_clinic_models
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());
